FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir poetry
RUN pip install --no-cache-dir django psycopg2-binary

COPY . .

CMD ["python", "src/manage.py", "runserver", "0.0.0.0:8000"]
